patient_id<-c("P001","P002","P003","P004","P005","P006")
age<-c(45,52,37,64,29,58)
sex<-c(1,2,2,1,1,2)
group<-c("control","treat","treat","control","treat","control")
height<-c(170,162,158,175,168,160)
weight<-c(70,61,55,82,68,59)
glucose<-c(5.6,7.8,NA,6.1,4.9,8.2)
class(age)
class(group)
class(sex)
sex_identify<-c(TRUE,FALSE,FALSE,TRUE,TRUE,FALSE)
class(sex_identify)
age[c(2,4,6)]
age[age>50]
a<-matrix(1:6,nrow=3)
b<-matrix(1:6,nrow=3,byrow=TRUE)
a
b
c<-array(1:12,c(2,3,2))
c
c[,,2]
patients<-data.frame(patient_id,age,sex,group,height,weight,glucose)
patients
str(patients)
dim(patients)
head(patients,3)
sex<-as.factor(sex,levels=c(1,2),labels=c("male","female"))
group<-as.factor(group)
summary(patients$group)
sex<-factor(sex,levels=c("1","2"),labels=c("male","female"))
group<-as.factor(group)
summary(patients$group)
summary(patients)
length(patients$group)
group<-factor(group,levels=c("control","treat"))
group_population<-table(group)
group_population
table(sex,group)
mean_age<-mean(age)
mean_weight<-mean(weight)
is.na(patients)
mean_age
mean_weight
na_count<-sum(is.na(patients))
patient_summary<-list(patients,mean_age,mean_weight,na_count)
patient_summary
patients<-as_tibble(patients)
patients
patients["age"]
patients$age
patients[age]
getwd()
write.csv(patients,"patients.csv",row.names=FALSE)
patients_from_csv<-read.csv("patients.csv",header = TRUE)
patients_from_csv
readxl::read_excel(system.file("extdata","datasets.xlsx",package = "readxl"),sheet="mtcars")
install.packages("readxl")
readxl::read_excel(system.file("extdata","datasets.xlsx",package = "readxl"),sheet="mtcars")
is.na(glucose)
labels(glucose,"may be blood sugar")
install.packages("Hmisc")
library(Hmisc)
label(glucose)<-"may be blood sugar"
glucose
ls()
d<-c(1,2,3,4)
mylist<-list(d,a,patients,sex)
mylist
mylist$d
mylist[[sex]]
mylist$age
mylist[[1]]
mylist[["sex"]]
mylist[sex]
sex
mylist[d]
savehistory(file=paste0("Whisper_week2_R_history_",format(Sys.time(),"%Y%m%d_%H%M%S"),"R.history"))